# frozen_string_literal: true
source 'https://supermarket.chef.io'
cookbook 'sudo', '~> 5.4.0'
cookbook 'users', '~> 5.4.0'
cookbook 'ohai', '~> 5.2.1'
cookbook 'oracle_java', '~> 0.2.1'
cookbook 'maven', '~> 5.2.0'
cookbook 'guava', '~> 19.0.0'
cookbook 'junit', '~> 4.12'
cookbook 'flywaydb','~> 0.1.3'
