#!/usr/bin/env python

from optparse import OptionParser
import sys
import gitlab

def main(opts, args):
    if 'add' in args or 'remove' in args and len(args) == 1:
        g = gitlab.Gitlab('https://git.5gdcs.com', opts.token, api_version=4) # set up gitlab client
        sys.exit(globals()[args[0]](g, opts.username, opts.pubkeyPath))
    else:
        sys.exit(2)

def add(client, user, pubkeyPath):
    try:
        client.users.list(username=user)[0].keys.create({
            'title': 'Generated by Chef on git.5gdcs.com',
            'key': open(pubkeyPath).read()
        })
    except gitlab.exceptions.GitlabCreateError as err:
        if not 'has already been taken' in str(err.error_message):
            raise
        else:
            return 0
    except:
        raise
    return 0

def remove(client, user, pubkeyPath):
    u = client.users.list(username=user)[0]
    #u.keys.list(key=open(pubkeyPath).read())[0].id
    if len(u.keys.list(key=open(pubkeyPath).read()))>0:
       u.keys.delete(u.keys.list(key=open(pubkeyPath).read())[0].id)
    return 0

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-u", "--username", dest="username", help="gitlab username to add pubkey to")
    parser.add_option("-p", "--pubkeyPath", dest="pubkeyPath", help="absolute path of pubkey to add")
    parser.add_option("-t", "--token", dest="token", help="private token for authenticating to gitlab api")
    (options, arguments) = parser.parse_args()
    main(options,arguments)
